### ISSUE TITLE
NoClassDefFoundError: com/tterrag/registrate/util/OneTimeEventReceiver

### ISSUE THREAD

**Issue by copygirl** [EDToaster/LittleContraptions#14]
Updated the mod to the newest version (1.18.2.1), now it crashes our server.

```
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
-- MOD littlecontraptions --
Details:
        Caused by 0: java.lang.reflect.InvocationTargetException
                at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:79) ~[?:?] {}
                at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
                at java.lang.reflect.Constructor.newInstance(Constructor.java:483) ~[?:?] {}
                at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:67) ~[javafmllanguage-1.18.2-40.1.68.jar%23195!/:?] {}
                at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[fmlcore-1.18.2-40.1.68.jar%23194!/:?] {}
                at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
                at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
                at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
                at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
                at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
                at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
                at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

        Caused by 1: java.lang.NoClassDefFoundError: com/tterrag/registrate/util/OneTimeEventReceiver
                at ca.edtoaster.littlecontraptions.setup.Registration.register(Registration.java:133) ~[littlecontraptions-forge-1.18.2.1.jar%23128!/:?] {re:classloading}
                at ca.edtoaster.littlecontraptions.LCMod.<init>(LCMod.java:20) ~[littlecontraptions-forge-1.18.2.1.jar%23128!/:?] {re:classloading}
                at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67) ~[?:?] {}
                at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
                at java.lang.reflect.Constructor.newInstance(Constructor.java:483) ~[?:?] {}
                at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:67) ~[javafmllanguage-1.18.2-40.1.68.jar%23195!/:?] {}
                at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[fmlcore-1.18.2-40.1.68.jar%23194!/:?] {}
                at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
                at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
                at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
                at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
                at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
                at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
                at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

        Mod File: /home/minecraft/heck/mods/littlecontraptions-forge-1.18.2.1.jar
        Failure message: Little Contraptions (littlecontraptions) has failed to load correctly
                java.lang.reflect.InvocationTargetException: null
        Mod Version: 1.18.2.1
        Mod Issue URL: https://github.com/EDToaster/LittleContraptions/issues
        Exception message: java.lang.ClassNotFoundException: com.tterrag.registrate.util.OneTimeEventReceiver
```

Let me know if you need any additional information such as our mod list.

**Comment by EDToaster** [comment]
Mod list would be great, I will take a look, thanks.

**Comment by muradakh** [comment]
Could you confirm that your create version is >=0.5d?

**Comment by copygirl** [comment]
> Could you confirm that your create version is >=0.5d?

Apologies, our auto-updater did not pick up on the new Create version for some reason, even though we updated all mods less than 4 days ago. I'll have a look if updating Create properly will resolve the issue.

**Comment by copygirl** [comment]
Alright that does seem to do the trick, apologies for the faulty bug report. I've reported the issue with the version checking / updating to packwiz (the tool we use).
